site_name: phy
pages:
- Home: 'index.md'
- Installation: 'install.md'
- User Guide:
   - 'Quick start': 'quick-start.md'
   - 'Working with Kwik files': 'kwik-model.md'
   - 'Interactive plotting': 'plot.md'
   - 'Manual clustering (KlustaViewa)': 'cluster-manual.md'
- API reference: 'api.md'
- Contact: 'contact.md'
theme: readthedocs
