site_name: phy
pages:
- Home / quick install: 'index.md'
- Advanced install: 'install.md'
- User Guide:
   - 'Quick start: spike sorting': 'quick-start.md'
   - 'Working with Kwik files': 'kwik-model.md'
   - 'Interactive plotting': 'plot.md'
   - 'Spike sorting session': 'cluster-auto.md'
   - 'Manual clustering GUI': 'cluster-manual.md'
- API reference: 'api.md'
- KWIK format description: 'kwik-format.md'
- Contact: 'contact.md'
theme: readthedocs
